### ISSUE TITLE
image taken from a camera

### ISSUE THREAD

**Issue by suspiciously36** [OurGuru/Offline-Reverse-Image-Search#5]
is there any way to search the image that is taken from a camera shot?

**Comment by OurGuru** [comment]
Theoretically yes but I guess you're referring to raw image file types like NEF that DSLR cameras save images as, which currently is not supported. The currently supported formats are ".jpg", ".jpeg", ".png", ".bmp", ".tif", ".tiff"

I have not considered other file types but I will include it on a future update. thanks!

**Comment by suspiciously36** [comment]
my situation is I have a high resolution picture stored on my hard disk, I took a picture of it by my camera from my phone, and the app cannot detect the picture by dragging the taken one from the phone to the app.
is there any possible way to do so?

**Comment by OurGuru** [comment]
I don't think there is any possible way at the moment if it's not already working.
Is the file format in the list of supported file formats that I listed above? If so please let me know the format of the file and the model of the phone so I can test it further as it would be bizarre
I will start working soon on an update to support more file types and fix various crashes

**Comment by suspiciously36** [comment]
i took picture with my iphone 12, idrk the format of taken picture maybe it's jpeg?![image](https://github.com/OurGuru/Offline-Reverse-Image-Search/assets/74701092/8f6b032c-7596-4c6e-aa2a-49f8d64dc700)
i take picture like this, remove all black screen to test if i can find exactly this picture on my own pc but i cannot

**Comment by OurGuru** [comment]
There is a significant difference of the image for the app compared to what we see. But it could be an interesting feature!

Closing this for now
